### ISSUE TITLE
Token not working? 

### ISSUE THREAD

**Issue by M7xz** [andrerahardjo97/discord-sticky-message-bot#4] opened 2021-01-27 07:50 UTC
keeps saying invalid token. 
![image](https://user-images.githubusercontent.com/66338380/105959788-5aabff80-604a-11eb-9172-b1d9578916a2.png)

**Comment by M7xz** [comment] 2021-01-27 07:50
i have checked the token and it works^

**Comment by M7xz** [comment] 2021-01-27 08:05
ok update i added client.login('token') to the index and it worked but the bot doesnt seem to work lol 
![image](https://user-images.githubusercontent.com/66338380/105961474-8c25ca80-604c-11eb-99bd-7ebb63ea6b75.png)

**Comment by M7xz** [comment] 2021-01-27 08:06
![image](https://user-images.githubusercontent.com/66338380/105961494-93e56f00-604c-11eb-98c8-31930cb27b7e.png)

**Comment by M7xz** [comment] 2021-01-27 08:16
i can see the bot online as the node works but none of the commands work.

**Comment by M7xz** [comment] 2021-01-27 08:16
i even put it back to - instead % for prefix

**Comment by andrerahardjo97** [comment] 2021-01-27 08:37
> ok update i added client.login('token') to the index and it worked but the bot doesnt seem to work lol
> ![image](https://user-images.githubusercontent.com/66338380/105961474-8c25ca80-604c-11eb-99bd-7ebb63ea6b75.png)
1. The `.env` file name should `.env` not `.env.env` (check your file name on that screenshot on your notepad title bar).
2. The `OWNER` value should be discord `user id`, not `username#discrim` (e.g. `160260681126213385`).
Right click on the username and choose `Copy ID`

**Comment by M7xz** [comment] 2021-01-28 03:29
how can i put it .env as the name it is not possible as windows read it as an extension

**Comment by M7xz** [comment] 2021-01-28 03:31
![image](https://user-images.githubusercontent.com/66338380/106086045-5d146500-60ef-11eb-966d-5278b03f4d30.png)

**Comment by M7xz** [comment] 2021-01-28 03:32
here is my .env 

DISCORD_TOKEN=censored
ALLOWED_ROLES_ID=
MAX_MESSAGE_COUNT=1
OWNER=581704871485636640
PREFIX=%

**Comment by M7xz** [comment] 2021-01-28 03:33
the sticky message does not work but i added new code in the bot like ban and stuff and those work so... I'm still confused 
![image](https://user-images.githubusercontent.com/66338380/106086195-b11f4980-60ef-11eb-9091-2f30365dbe69.png) 
![image](https://user-images.githubusercontent.com/66338380/106086209-b7152a80-60ef-11eb-976b-938eca8f3146.png)

**Comment by M7xz** [comment] 2021-01-28 03:34
and the prefix isnt working btw^^ i put a custom command with "%ban" that makes that run!^

**Comment by M7xz** [comment] 2021-01-28 03:36
index file still has

 require("dotenv").config();
const Discord = require("discord.js");
const client = new Discord.Client({
  ws: {
    intents: [
      "GUILDS",
      "GUILD_MESSAGES",
    ],
  },
});

**Comment by andrerahardjo97** [comment] 2021-01-28 07:01
The file name should only an extension. And when you open it with notepad, it should be `.env` in title bar, **not** `.env.env`
Just as I said, the bot not working because it cannot read the `.env` file, because you name it `.env.env`.
The code cannot read the `.env` file and of course the code don't know the prefix that you use.

**Comment by andrerahardjo97** [comment] 2021-01-28 07:03
Below is the image how you should name the `.env` file.
![2021-01-28_14-02-48](https://user-images.githubusercontent.com/20762999/106102209-a2797680-6171-11eb-9a88-ff4d3b57d9f1.png)

**Comment by M7xz** [comment] 2021-01-28 13:55
![image](https://user-images.githubusercontent.com/66338380/106148015-8ca28c00-6146-11eb-9a1d-b1b05fcef2d9.png)

**Comment by M7xz** [comment] 2021-01-28 13:55
how do u even make that file..

**Comment by M7xz** [comment] 2021-01-28 14:02
![image](https://user-images.githubusercontent.com/66338380/106148839-882aa300-6147-11eb-81bb-00e60e6c7ca4.png)
 still does not work

**Comment by M7xz** [comment] 2021-01-28 14:12
nevermind i have fixed it! but a quick question for the sticky is it possible in the future where you can allow multiple servers sticky? or channels.

**Comment by M7xz** [comment] 2021-01-28 14:20
Okay so i put MAX_MESSAGE_COUNT=5 and now the bot broken

**Comment by andrerahardjo97** [comment] 2021-01-28 14:33
> nevermind i have fixed it! but a quick question for the sticky is it possible in the future where you can allow multiple servers sticky? or channels.
Nope, make yourself, this is just a simple bot and doesn't have any new features.



> Okay so i put MAX_MESSAGE_COUNT=5 and now the bot broken
This is the default settting in `.env` file, and it's impossible for the bot to broken just because you put number `5`.
https://github.com/andrerahardjo97/discord-sticky-message-bot/blob/main/.env.example

Proof that the bot is work: https://gyazo.com/6b28a394d4a60887e6d088a6ad6c1ecd

**Comment by andrerahardjo97** [comment] 2021-01-28 14:41
I'm closing this issue, since the bot is working fine and this is just installation issue.
As I said in **support** section on `README.md`, I actually don't offer installation support or respond on installation issue.
If you still doubt the bot is work or not, send a proof that the code is the cause that the bot doesn't work.

**Closed by andrerahardjo97** 2021-01-28 14:41 UTC
Labels: user errror
